# Generated by Django 4.2.11 on 2024-05-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('architecture', models.JSONField()),
                ('learning_rate', models.FloatField()),
                ('loss', models.CharField(max_length=100)),
                ('epochs', models.IntegerField()),
                ('batch_size', models.IntegerField()),
                ('validation_split', models.FloatField()),
            ],
        ),
    ]
