# Generated by Django 4.2.11 on 2024-05-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_modelparameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelparameters',
            name='name',
            field=models.CharField(default='atual', max_length=100),
        ),
    ]
